"use client";

import * as React from "react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { addMonths, eachDayOfInterval, endOfMonth, endOfWeek, format, isSameDay, isSameMonth, startOfMonth, startOfWeek, subMonths } from "date-fns";
import { ru } from "date-fns/locale";
import { BookOpen, CalendarCheck2, CalendarPlus, ChevronLeft, ChevronRight, Plus, Search, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { compareLessonsChronologically, lessonKindLabels, lessonNumberLabel } from "@/lib/planner-utils";
import { cn } from "@/lib/utils";
import { TaskDialog } from "./editor-dialogs";
import { usePlanner } from "./planner-provider";
import { PageHeading, Panel, PanelHeader, SubjectDot, TaskItem } from "./view-shared";

export function TasksView({ onAddTask }: { onAddTask: () => void }) {
  const { state } = usePlanner(); const router = useRouter(); const searchParams = useSearchParams(); const [query, setQuery] = React.useState(""); const [subject, setSubject] = React.useState("all"); const [status, setStatus] = React.useState("open");
  const requested = searchParams.get("task"); const queryTask = state.tasks.find((task) => task.id === requested) ?? null;
  const tasks = state.tasks.filter((task) => (!query || `${task.title} ${task.notes}`.toLowerCase().includes(query.toLowerCase())) && (subject === "all" || task.subjectId === subject) && (status === "all" || status === "open" && task.status !== "done" || task.status === status));
  return <main className="mx-auto w-full max-w-[1180px] space-y-4 px-3 pb-28 pt-4 sm:px-5 lg:px-7 lg:pb-10"><PageHeading title="Дедлайны" action={<Button onClick={onAddTask}><Plus />Добавить</Button>} /><Panel className="p-3"><div className="grid gap-2.5 md:grid-cols-[minmax(220px,1fr)_220px_180px]"><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Поиск" className="pl-9" /></div><Select value={subject} onValueChange={setSubject}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Все предметы</SelectItem>{state.subjects.map((item) => <SelectItem key={item.id} value={item.id}>{item.shortTitle}</SelectItem>)}</SelectContent></Select><Select value={status} onValueChange={setStatus}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="open">Открытые</SelectItem><SelectItem value="all">Все</SelectItem><SelectItem value="todo">Нужно сделать</SelectItem><SelectItem value="doing">В работе</SelectItem><SelectItem value="done">Готово</SelectItem></SelectContent></Select></div></Panel><Panel className="space-y-2 p-2">{tasks.map((task) => <TaskItem key={task.id} task={task} />)}{!tasks.length ? <p className="p-4 text-muted-foreground">Ничего не найдено</p> : null}</Panel><TaskDialog open={Boolean(queryTask)} onOpenChange={(value) => { if (!value) router.replace("/tasks"); }} task={queryTask} /></main>;
}

export function CalendarView({ onAddTask }: { onAddTask: () => void }) {
  const { state } = usePlanner();
  const [month, setMonth] = React.useState(startOfMonth(new Date()));
  const [selected, setSelected] = React.useState(new Date());
  const start = startOfWeek(startOfMonth(month), { weekStartsOn: 1 }); const end = endOfWeek(endOfMonth(month), { weekStartsOn: 1 }); const days = eachDayOfInterval({ start, end });
  const selectedTasks = state.tasks.filter((task) => isSameDay(new Date(task.dueDate), selected));
  const selectedLessons = state.lessons.filter((lesson) => lesson.date && isSameDay(new Date(lesson.date), selected)).sort(compareLessonsChronologically);
  const selectedActivities = state.activities.filter((activity) => isSameDay(new Date(activity.date), selected)).sort((a, b) => a.date.localeCompare(b.date));
  const selectedLessonDeadlines = state.lessons.filter((lesson) => lesson.deadline && isSameDay(new Date(lesson.deadline), selected)).sort((a, b) => a.deadline!.localeCompare(b.deadline!));
  const selectedDeadlines = [...selectedTasks.map((task) => ({ kind: "task" as const, id: task.id, at: task.dueDate, task })), ...selectedLessonDeadlines.map((lesson) => ({ kind: "lesson" as const, id: lesson.id, at: lesson.deadline!, lesson }))].sort((a, b) => a.at.localeCompare(b.at));

  return <main className="mx-auto w-full max-w-[1400px] space-y-4 px-3 pb-28 pt-4 sm:px-5 lg:px-7 lg:pb-10"><PageHeading title="Календарь" action={<Button onClick={onAddTask}><CalendarPlus />Дедлайн</Button>} /><div className="grid gap-3 xl:grid-cols-[minmax(0,1.6fr)_360px]">
    <Panel className="overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-2 border-b border-border/60 px-3 py-3 sm:px-4"><h2 className="text-lg font-semibold capitalize">{format(month, "LLLL yyyy", { locale: ru })}</h2><div className="flex items-center gap-1"><Button variant="ghost" size="icon" onClick={() => setMonth(subMonths(month, 1))}><ChevronLeft /></Button><Button variant="outline" size="sm" onClick={() => { setMonth(startOfMonth(new Date())); setSelected(new Date()); }}>Сегодня</Button><Button variant="ghost" size="icon" onClick={() => setMonth(addMonths(month, 1))}><ChevronRight /></Button></div><div className="calendar-legend flex w-full flex-wrap gap-3 text-[11px] text-muted-foreground"><span><i className="bg-[#0050CF]" />Занятия</span><span><i className="bg-[#D92D20]" />Дедлайны</span><span><i className="bg-[#008B6B]" />Активности</span></div></div><div className="calendar-grid"><div className="grid grid-cols-7 border-b border-border/60 bg-muted">{["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"].map((day) => <span key={day} className="py-2 text-center text-xs font-medium text-muted-foreground">{day}</span>)}</div><div className="grid grid-cols-7">{days.map((day) => {
      const deadlines = state.tasks.filter((task) => isSameDay(new Date(task.dueDate), day));
      const lessons = state.lessons.filter((lesson) => lesson.date && isSameDay(new Date(lesson.date), day)).sort(compareLessonsChronologically);
      const lessonDeadlines = state.lessons.filter((lesson) => lesson.deadline && isSameDay(new Date(lesson.deadline), day));
      const activities = state.activities.filter((activity) => isSameDay(new Date(activity.date), day));
      const events = [
        ...lessons.map((lesson) => ({ id: lesson.id, kind: "lesson" as const, at: lesson.date!, title: `${lessonKindLabels[lesson.kind]} ${lessonNumberLabel(lesson)}`, href: `/subjects/${lesson.subjectId}?lesson=${lesson.id}` })),
        ...deadlines.map((task) => ({ id: task.id, kind: "deadline" as const, at: task.dueDate, title: task.title, href: `/tasks?task=${task.id}` })),
        ...lessonDeadlines.map((lesson) => ({ id: `lesson-${lesson.id}`, kind: "deadline" as const, at: lesson.deadline!, title: `К занятию: ${lesson.title || `${lessonKindLabels[lesson.kind]} ${lessonNumberLabel(lesson)}`}`, href: `/subjects/${lesson.subjectId}?lesson=${lesson.id}` })),
        ...activities.map((activity) => ({ id: activity.id, kind: "activity" as const, at: activity.date, title: activity.title, href: "/activities" })),
      ].sort((a, b) => a.at.localeCompare(b.at));
      return <div key={day.toISOString()} className={cn("calendar-day min-h-28 border-b border-r border-border/55 p-1.5", !isSameMonth(day, month) && "calendar-day-outside", isSameDay(day, selected) && "calendar-day-selected")}><button onClick={() => setSelected(day)} className={cn("grid size-7 place-items-center rounded-full text-sm", isSameDay(day, new Date()) && "bg-[#0050CF] font-semibold text-white")}>{format(day, "d")}</button><div className="mt-1 space-y-1">{events.slice(0, 4).map((event) => <Link key={`${event.kind}-${event.id}`} href={event.href} onClick={() => setSelected(day)} title={`${event.title} · ${format(new Date(event.at), "HH:mm")}`} className={cn("calendar-event flex min-w-0 items-center gap-1.5 rounded-md px-1.5 py-1 text-[10px]", event.kind === "lesson" ? "calendar-event-lesson" : event.kind === "activity" ? "calendar-event-activity" : "calendar-event-deadline")}>{event.kind === "lesson" ? <BookOpen className="size-3 shrink-0" /> : event.kind === "activity" ? <Sparkles className="size-3 shrink-0" /> : <CalendarCheck2 className="size-3 shrink-0" />}<span className="calendar-event-label truncate">{event.title}</span><span className="calendar-event-time ml-auto shrink-0 opacity-65">{format(new Date(event.at), "HH:mm")}</span></Link>)}{events.length > 4 ? <button onClick={() => setSelected(day)} className="px-1 text-[10px] text-muted-foreground">+{events.length - 4}</button> : null}</div></div>;
    })}</div></div></Panel>
    <Panel className="h-fit overflow-hidden xl:sticky xl:top-18"><PanelHeader title={format(selected, "d MMMM, EEEE", { locale: ru })} /><div className="space-y-3 p-2.5"><section><div className="mb-1.5 flex items-center gap-2 px-1 text-xs font-semibold text-muted-foreground"><BookOpen className="size-3.5" />Занятия</div><div className="space-y-1.5">{selectedLessons.map((lesson) => { const subject = state.subjects.find((item) => item.id === lesson.subjectId); return <Link key={lesson.id} href={`/subjects/${lesson.subjectId}?lesson=${lesson.id}`} className="calendar-side-item flex items-center gap-2 rounded-[11px] p-2"><SubjectDot subject={subject} /><span className="min-w-0 flex-1 truncate text-sm font-semibold">{lessonKindLabels[lesson.kind]} {lessonNumberLabel(lesson)}</span><span className="text-xs text-muted-foreground">{lesson.date ? format(new Date(lesson.date), "HH:mm") : ""}</span></Link>; })}{!selectedLessons.length ? <p className="px-2 py-1 text-sm text-muted-foreground">Нет занятий</p> : null}</div></section><section className="border-t border-border/50 pt-2.5"><div className="mb-1.5 flex items-center gap-2 px-1 text-xs font-semibold text-muted-foreground"><CalendarCheck2 className="size-3.5" />Дедлайны</div><div className="space-y-1.5">{selectedDeadlines.map((event) => event.kind === "task" ? <TaskItem key={`task-${event.id}`} task={event.task} dense /> : (() => { const lesson = event.lesson; const subject = state.subjects.find((item) => item.id === lesson.subjectId); return <Link key={`lesson-${event.id}`} href={`/subjects/${lesson.subjectId}?lesson=${lesson.id}`} className="calendar-side-item flex items-center gap-2 rounded-[11px] p-2"><SubjectDot subject={subject} /><span className="min-w-0 flex-1 truncate text-sm font-semibold">{lesson.title || `${lessonKindLabels[lesson.kind]} ${lessonNumberLabel(lesson)}`}</span><span className="text-xs text-muted-foreground">{format(new Date(event.at), "HH:mm")}</span></Link>; })())}{!selectedDeadlines.length ? <p className="px-2 py-1 text-sm text-muted-foreground">Нет дедлайнов</p> : null}</div></section><section className="border-t border-border/50 pt-2.5"><div className="mb-1.5 flex items-center gap-2 px-1 text-xs font-semibold text-muted-foreground"><Sparkles className="size-3.5" />Активности</div><div className="space-y-1.5">{selectedActivities.map((activity) => <Link key={activity.id} href="/activities" className="calendar-side-item flex items-center gap-2 rounded-[11px] p-2"><span className="grid size-4 place-items-center rounded-[5px] bg-emerald-600 text-white"><Sparkles className="size-2.5" /></span><span className="min-w-0 flex-1 truncate text-sm font-semibold">{activity.title}</span><span className="text-xs text-muted-foreground">{format(new Date(activity.date), "HH:mm")}</span></Link>)}{!selectedActivities.length ? <p className="px-2 py-1 text-sm text-muted-foreground">Нет активностей</p> : null}</div></section></div></Panel>
  </div></main>;
}
