"use client";

/* eslint-disable react-hooks/set-state-in-effect -- Dialog drafts reset when a grade opens. */

import * as React from "react";
import Link from "next/link";
import { format } from "date-fns";
import { ru } from "date-fns/locale";
import { Activity as ActivityIcon, ArrowDown, ArrowUp, BriefcaseBusiness, Check, Download, ExternalLink, GraduationCap, Moon, MoreHorizontal, Pencil, Plus, RefreshCcw, Settings2, Sparkles, Sun, Trash2, Upload, Users } from "lucide-react";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import type { Activity, DiplomaGrade, Material, Subject, ThesisState } from "@/lib/planner-types";
import { compareSubjectsByStudyOrder, formatSubjectModules, uid } from "@/lib/planner-utils";
import { cn } from "@/lib/utils";
import { ActivityDialog, MaterialDialog, SubjectDialog } from "./editor-dialogs";
import { usePlanner } from "./planner-provider";
import { SubjectIcon } from "./subject-icon";
import { MaterialCard, PageHeading, Panel, PanelHeader, SubjectDot } from "./view-shared";
import { UploadDialog } from "./views-grades-materials";

type WorkKey = "coursework" | "thesis";

function WorkEditor({ workKey }: { workKey: WorkKey }) {
  const { state, mutate } = usePlanner();
  const [uploadOpen, setUploadOpen] = React.useState(false);
  const [linkOpen, setLinkOpen] = React.useState(false);
  const work: ThesisState = state[workKey];
  const scope: Material["scope"] = workKey === "coursework" ? "coursework" : "thesis";
  const materials = state.materials.filter((item) => item.scope === scope);
  const addBlock = () => mutate((draft) => { draft[workKey].blocks.push({ id: uid(`${workKey}-block`), title: "Новый блок", content: "" }); });
  const moveBlock = (index: number, direction: -1 | 1) => mutate((draft) => {
    const blocks = draft[workKey].blocks; const target = index + direction;
    if (target < 0 || target >= blocks.length) return;
    [blocks[index], blocks[target]] = [blocks[target], blocks[index]];
  });

  return <div className="space-y-2.5">
    <Panel>
      <PanelHeader title="Файлы и ссылки" action={<div className="flex gap-1"><Button variant="ghost" size="sm" onClick={() => setLinkOpen(true)}><Plus />Ссылка</Button><Button variant="ghost" size="sm" onClick={() => setUploadOpen(true)}><Upload />Файл</Button></div>} />
      <div className="grid gap-2 p-2.5 sm:grid-cols-2">{materials.map((item) => <MaterialCard key={item.id} material={item} compact />)}{!materials.length ? <p className="px-1 py-1.5 text-sm text-muted-foreground">Пока пусто</p> : null}</div>
    </Panel>
    <Panel className="thesis-title-card relative overflow-hidden p-3.5">
      <Label htmlFor={`${workKey}-title`} className="text-white/75">Название работы</Label>
      <Input id={`${workKey}-title`} value={work.title} onChange={(event) => mutate((draft) => { draft[workKey].title = event.target.value; })} className="mt-1.5 h-10 border-white bg-white px-3 text-lg font-semibold text-[#111827] sm:text-xl" />
    </Panel>
    <div className="space-y-2">{work.blocks.map((block, index) => <Panel key={block.id} className="thesis-card group p-2.5" style={{ "--card-accent": ["#0050cf", "#7c3aed", "#00a878", "#f04438", "#f97316", "#e0a000", "#008ed6", "#e53683"][index % 8] } as React.CSSProperties}>
      <div className="flex items-start gap-2"><div className="min-w-0 flex-1"><Label htmlFor={`${workKey}-block-${block.id}`} className="text-[11px] text-muted-foreground">Название части</Label><div className="relative mt-1"><Input id={`${workKey}-block-${block.id}`} value={block.title} onChange={(event) => mutate((draft) => { const item = draft[workKey].blocks.find((current) => current.id === block.id); if (item) item.title = event.target.value; })} className="h-8 border-border/60 bg-card pr-9 text-sm font-semibold" /><Pencil className="pointer-events-none absolute right-3 top-1/2 size-3.5 -translate-y-1/2 text-muted-foreground" /></div><Textarea aria-label={`Содержание ${block.title}`} value={block.content} onChange={(event) => mutate((draft) => { const item = draft[workKey].blocks.find((current) => current.id === block.id); if (item) item.content = event.target.value; })} className="mt-1.5 min-h-16 resize-y border-border/50 bg-card text-sm leading-5" /></div><div className="flex flex-col gap-0.5"><Button variant="ghost" size="icon" className="size-7" disabled={index === 0} onClick={() => moveBlock(index, -1)} aria-label="Переместить выше"><ArrowUp /></Button><Button variant="ghost" size="icon" className="size-7" disabled={index === work.blocks.length - 1} onClick={() => moveBlock(index, 1)} aria-label="Переместить ниже"><ArrowDown /></Button><Button variant="ghost" size="icon" className="size-7 text-destructive" onClick={() => mutate((draft) => { draft[workKey].blocks = draft[workKey].blocks.filter((item) => item.id !== block.id); })} aria-label="Удалить блок"><Trash2 /></Button></div></div>
    </Panel>)}</div>
    <Button variant="outline" size="sm" onClick={addBlock}><Plus />Блок</Button>
    <UploadDialog open={uploadOpen} onOpenChange={setUploadOpen} defaultScope={scope} />
    <MaterialDialog open={linkOpen} onOpenChange={setLinkOpen} defaultScope={scope} />
  </div>;
}

export function ThesisView() {
  const [workKey, setWorkKey] = React.useState<WorkKey>("coursework");
  return <main className="mx-auto w-full max-w-[1120px] space-y-3.5 px-3 pb-28 pt-4 sm:px-5 lg:px-7 lg:pb-10">
    <PageHeading title="КР и ВКР" action={<Tabs value={workKey} onValueChange={(value) => setWorkKey(value as WorkKey)}><TabsList><TabsTrigger value="coursework">Курсовая · 1 курс</TabsTrigger><TabsTrigger value="thesis">ВКР</TabsTrigger></TabsList></Tabs>} />
    <WorkEditor workKey={workKey} />
  </main>;
}

function DiplomaGradeDialog({ open, onOpenChange, item, defaultYear }: { open: boolean; onOpenChange: (open: boolean) => void; item?: DiplomaGrade | null; defaultYear: 1 | 2 }) {
  const { mutate } = usePlanner();
  const [subject, setSubject] = React.useState(""); const [grade, setGrade] = React.useState(""); const [year, setYear] = React.useState<1 | 2>(defaultYear); const [module, setModule] = React.useState<1 | 2 | 3 | 4>(1);
  React.useEffect(() => { if (!open) return; setSubject(item?.subject ?? ""); setGrade(item?.grade ?? ""); setYear(item?.year ?? defaultYear); setModule(item?.module ?? 1); }, [defaultYear, item, open]);
  function submit(event: React.FormEvent) { event.preventDefault(); if (!subject.trim()) return; mutate((draft) => { const next: DiplomaGrade = { id: item?.id ?? uid("diploma-grade"), subject: subject.trim(), grade: grade.trim(), year, module }; const index = draft.diplomaGrades.findIndex((current) => current.id === next.id); if (index >= 0) draft.diplomaGrades[index] = next; else draft.diplomaGrades.push(next); }); onOpenChange(false); }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-lg"><form onSubmit={submit} className="grid gap-4"><DialogHeader><DialogTitle>{item ? "Изменить итоговую оценку" : "Добавить итоговую оценку"}</DialogTitle></DialogHeader><div className="grid gap-3 sm:grid-cols-2"><div className="grid gap-1.5"><Label>Курс</Label><Select value={String(year)} onValueChange={(value) => setYear(Number(value) as 1 | 2)}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="1">1 курс</SelectItem><SelectItem value="2">2 курс</SelectItem></SelectContent></Select></div><div className="grid gap-1.5"><Label>Модуль</Label><Select value={String(module)} onValueChange={(value) => setModule(Number(value) as 1 | 2 | 3 | 4)}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent>{[1, 2, 3, 4].map((value) => <SelectItem key={value} value={String(value)}>Модуль {value}</SelectItem>)}</SelectContent></Select></div></div><div className="grid gap-1.5"><Label>Дисциплина</Label><Input value={subject} onChange={(event) => setSubject(event.target.value)} autoFocus /></div><div className="grid gap-1.5"><Label>Итоговая оценка</Label><Input value={grade} onChange={(event) => setGrade(event.target.value)} placeholder="10, зачёт, отлично…" /></div><DialogFooter><Button type="button" variant="ghost" onClick={() => onOpenChange(false)}>Отмена</Button><Button type="submit">Сохранить</Button></DialogFooter></form></DialogContent></Dialog>;
}

export function DiplomaView() {
  const { state, mutate } = usePlanner(); const [year, setYear] = React.useState<1 | 2>(1); const [selected, setSelected] = React.useState<DiplomaGrade | null | undefined>(undefined);
  return <main className="mx-auto w-full max-w-[1120px] space-y-3.5 px-3 pb-28 pt-4 sm:px-5 lg:px-7 lg:pb-10"><PageHeading title="Диплом" action={<div className="flex items-center gap-2"><Tabs value={String(year)} onValueChange={(value) => setYear(Number(value) as 1 | 2)}><TabsList><TabsTrigger value="1">1 курс</TabsTrigger><TabsTrigger value="2">2 курс</TabsTrigger></TabsList></Tabs><Button onClick={() => setSelected(null)}><Plus />Оценка</Button></div>} />
    <div className="space-y-2">{[1, 2, 3, 4].map((module) => { const rows = state.diplomaGrades.filter((item) => item.year === year && item.module === module); return <Panel key={module} className="module-list-block overflow-hidden"><PanelHeader title={`${module} модуль`} /><div className="divide-y divide-border/50">{rows.map((item) => <div key={item.id} className="flex items-center gap-2 px-3 py-2"><button className="min-w-0 flex-1 truncate text-left text-sm font-semibold hover:underline" onClick={() => setSelected(item)}>{item.subject}</button><span className="rounded-lg bg-muted px-2.5 py-1 text-sm font-semibold">{item.grade || "—"}</span><Button variant="ghost" size="icon" className="size-7 text-destructive" onClick={() => mutate((draft) => { draft.diplomaGrades = draft.diplomaGrades.filter((current) => current.id !== item.id); })}><Trash2 /></Button></div>)}{!rows.length ? <p className="px-3 py-2.5 text-sm text-muted-foreground">Нет оценок</p> : null}</div></Panel>; })}</div>
    <DiplomaGradeDialog open={selected !== undefined} onOpenChange={(value) => { if (!value) setSelected(undefined); }} item={selected} defaultYear={year} />
  </main>;
}

const activityMeta = {
  magolego: { label: "МагоЛего", icon: Sparkles, color: "#7c3aed" }, internship: { label: "Практика", icon: BriefcaseBusiness, color: "#00a878" }, career: { label: "Карьера", icon: GraduationCap, color: "#f04438" }, club: { label: "Клуб", icon: Users, color: "#0050cf" }, event: { label: "Мероприятие", icon: ActivityIcon, color: "#f97316" },
};

export function ActivitiesView({ onAddActivity }: { onAddActivity: () => void }) {
  const { state, mutate } = usePlanner(); const [filter, setFilter] = React.useState("all"); const [selected, setSelected] = React.useState<Activity | null>(null); const activities = state.activities.filter((item) => filter === "all" || item.category === filter).sort((a, b) => a.date.localeCompare(b.date));
  return <main className="mx-auto w-full max-w-[1300px] space-y-6 px-4 pb-28 pt-7 sm:px-6 lg:px-8 lg:pb-12"><PageHeading title="Активности" action={<Button onClick={onAddActivity}><Plus />Добавить</Button>} /><div className="flex gap-2 overflow-x-auto pb-1">{[{ value: "all", label: "Все" }, { value: "magolego", label: "МагоЛего" }, { value: "internship", label: "Практика" }, { value: "career", label: "Карьера" }, { value: "club", label: "Клубы" }, { value: "event", label: "События" }].map((item) => <Button key={item.value} variant={filter === item.value ? "default" : "outline"} size="sm" className="shrink-0" onClick={() => setFilter(item.value)}>{item.label}</Button>)}</div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{activities.map((activity) => { const meta = activityMeta[activity.category]; const Icon = meta.icon; return <Panel key={activity.id} className="activity-card group p-5 pl-6" style={{ "--card-accent": meta.color } as React.CSSProperties}><div className="flex items-start gap-3"><span className="card-accent-icon grid size-11 shrink-0 place-items-center rounded-xl"><Icon className="size-5" /></span><div className="min-w-0 flex-1"><Badge variant="secondary">{meta.label}</Badge><h2 className="mt-3 text-xl font-semibold tracking-[-.03em]">{activity.title}</h2></div><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" className="size-8 opacity-45 group-hover:opacity-100"><MoreHorizontal /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onSelect={() => setSelected(activity)}><Pencil />Изменить</DropdownMenuItem><DropdownMenuItem className="text-destructive" onSelect={() => mutate((draft) => { draft.activities = draft.activities.filter((item) => item.id !== activity.id); })}><Trash2 />Удалить</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div>{activity.notes ? <p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-muted-foreground">{activity.notes}</p> : null}<div className="mt-5 flex items-center gap-2"><Select value={activity.status} onValueChange={(value) => mutate((draft) => { const item = draft.activities.find((current) => current.id === activity.id); if (item) item.status = value as Activity["status"]; })}><SelectTrigger className="h-8 w-36"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="todo">Запланировано</SelectItem><SelectItem value="doing">В процессе</SelectItem><SelectItem value="done">Завершено</SelectItem></SelectContent></Select><span className="ml-auto text-sm text-muted-foreground">{format(new Date(activity.date), "d MMM yyyy", { locale: ru })}</span>{activity.link ? <Button asChild variant="ghost" size="icon"><a href={activity.link} target="_blank" rel="noreferrer"><ExternalLink /></a></Button> : null}</div></Panel>; })}</div><ActivityDialog open={Boolean(selected)} onOpenChange={(value) => { if (!value) setSelected(null); }} activity={selected} /></main>;
}

export function SettingsView({ onAddSubject }: { onAddSubject: () => void }) {
  const { state, mutate, removeSubject, exportData, importData, resetData } = usePlanner(); const [editing, setEditing] = React.useState<Subject | null>(null); const importRef = React.useRef<HTMLInputElement>(null);
  const subjects = state.subjects.slice().sort(compareSubjectsByStudyOrder);
  return <main className="mx-auto w-full max-w-[1120px] space-y-4 px-3 pb-28 pt-4 sm:px-5 lg:px-7 lg:pb-10"><PageHeading title="Настройки" /><Panel><PanelHeader title="Учебный профиль" /><div className="grid gap-3 p-3 sm:grid-cols-2"><div className="grid gap-1.5"><Label>Имя</Label><Input value={state.profile.name} onChange={(event) => mutate((draft) => { draft.profile.name = event.target.value; })} /></div><div className="grid gap-1.5"><Label>Программа</Label><Input value={state.profile.program} onChange={(event) => mutate((draft) => { draft.profile.program = event.target.value; })} /></div><div className="grid gap-1.5"><Label>Учебный год</Label><Input value={state.profile.academicYear} onChange={(event) => mutate((draft) => { draft.profile.academicYear = event.target.value; })} /></div><div className="grid gap-1.5"><Label>Текущий курс</Label><Select value={String(state.profile.year)} onValueChange={(value) => mutate((draft) => { draft.profile.year = Number(value); })}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="1">1 курс</SelectItem><SelectItem value="2">2 курс</SelectItem></SelectContent></Select></div></div></Panel>
    <Panel><PanelHeader title="Дисциплины" action={<Button size="sm" onClick={onAddSubject}><Plus />Добавить</Button>} /><div className="hidden sm:block"><Table><TableHeader><TableRow><TableHead>Предмет</TableHead><TableHead>Курс</TableHead><TableHead>Тип</TableHead><TableHead>Модули</TableHead><TableHead>Кредиты</TableHead><TableHead className="w-24" /></TableRow></TableHeader><TableBody>{subjects.map((subject) => <TableRow key={subject.id}><TableCell><Link href={`/subjects/${subject.id}`} className="flex items-center gap-3 font-medium hover:underline"><SubjectDot subject={subject} />{subject.title}</Link></TableCell><TableCell>{subject.year}</TableCell><TableCell>{subject.status === "required" ? "Обязательный" : subject.status === "elective" ? "По выбору" : "МагоЛего"}</TableCell><TableCell>{formatSubjectModules(subject)}</TableCell><TableCell>{subject.credits}</TableCell><TableCell><div className="flex justify-end"><Button variant="ghost" size="icon" onClick={() => setEditing(subject)}><Pencil /></Button><AlertDialog><AlertDialogTrigger asChild><Button variant="ghost" size="icon" className="text-destructive"><Trash2 /></Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Удалить дисциплину?</AlertDialogTitle><AlertDialogDescription>Будут удалены связанные занятия, дедлайны, оценки и материалы.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Отмена</AlertDialogCancel><AlertDialogAction className="bg-destructive text-white" onClick={() => void removeSubject(subject.id)}>Удалить</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div></TableCell></TableRow>)}</TableBody></Table></div><div className="divide-y sm:hidden">{subjects.map((subject) => <div key={subject.id} className="flex items-center gap-3 p-3"><span className="grid size-9 place-items-center rounded-xl text-white" style={{ backgroundColor: subject.color }}><SubjectIcon subject={subject} /></span><div className="min-w-0 flex-1"><p className="truncate font-medium">{subject.shortTitle}</p><p className="text-xs text-muted-foreground">{subject.year} курс · {subject.status === "required" ? "Обязательный" : subject.status === "elective" ? "По выбору" : "МагоЛего"} · {formatSubjectModules(subject)}</p></div><Button variant="ghost" size="icon" onClick={() => setEditing(subject)}><Pencil /></Button></div>)}</div></Panel>
    <Panel><PanelHeader title="Оформление" /><div className="grid gap-3 p-5 sm:grid-cols-3">{([{ value: "light", label: "Светлая", icon: Sun }, { value: "dark", label: "Тёмная", icon: Moon }, { value: "system", label: "Как в системе", icon: Settings2 }] as const).map((item) => <button key={item.value} onClick={() => mutate((draft) => { draft.profile.theme = item.value; })} className={cn("flex items-center gap-3 rounded-2xl border p-4 text-left", state.profile.theme === item.value && "border-[#0050CF] bg-[#0050CF]/6")}><item.icon className="size-5" /><span className="font-medium">{item.label}</span>{state.profile.theme === item.value ? <Check className="ml-auto size-4 text-[#0050CF]" /> : null}</button>)}</div></Panel>
    <Panel><PanelHeader title="Резервная копия" /><div className="grid gap-3 p-5 sm:grid-cols-2"><Button variant="outline" className="justify-start" onClick={exportData}><Download />Скачать JSON</Button><input ref={importRef} type="file" accept="application/json" className="sr-only" onChange={(event) => { const file = event.target.files?.[0]; if (file) void importData(file); event.target.value = ""; }} /><Button variant="outline" className="justify-start" onClick={() => importRef.current?.click()}><Upload />Восстановить из JSON</Button></div><div className="border-t border-border/60 p-5"><AlertDialog><AlertDialogTrigger asChild><Button variant="ghost" className="text-destructive"><RefreshCcw />Сбросить данные</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Сбросить весь планер?</AlertDialogTitle><AlertDialogDescription>Текущие данные будут заменены исходным шаблоном.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Отмена</AlertDialogCancel><AlertDialogAction className="bg-destructive text-white" onClick={() => void resetData()}>Сбросить</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div></Panel><SubjectDialog open={Boolean(editing)} onOpenChange={(value) => { if (!value) setEditing(null); }} subject={editing} /></main>;
}
