import { addDays, addMonths, formatISO, startOfDay } from "date-fns";
import type { CourseLesson, CourseTopic, PlannerState, Subject } from "./planner-types";

function iso(base: Date, days: number, hour = 18) {
  const result = addDays(startOfDay(base), days);
  result.setHours(hour, 0, 0, 0);
  return formatISO(result);
}

const subjects: Subject[] = [
  {
    id: "ai-media",
    title: "Искусственный интеллект в медиакоммуникациях и медиаисследованиях",
    shortTitle: "ИИ в медиа",
    emoji: "✦",
    color: "#2563EB",
    pattern: "grid",
    module: 2,
    year: 1,
    credits: 3,
    status: "required",
    language: "RU",
    scheduleLabel: "Вт, 18:10",
    room: "Покровский б-р, 11 · R403",
    description: "ИИ-инструменты для медиапроизводства, исследований и проектирования индустриальных решений.",
    objectives: ["Промпт-инжиниринг", "Анализ медиаконтента", "Этика и регулирование ИИ", "Прототип индустриального решения"],
    sourceUrl: "https://www.hse.ru/ma/mediaman/courses/1163626217.html",
    targetGrade: 9,
    roundingRule: "math",
    pinned: true,
  },
  {
    id: "research-seminar",
    title: "НИС «Методология и методы медиаисследований»",
    shortTitle: "НИС",
    emoji: "⌁",
    color: "#7448D8",
    pattern: "orbit",
    module: 2,
    modules: [1, 2, 3, 4],
    year: 1,
    credits: 6,
    status: "required",
    language: "RU",
    scheduleLabel: "Ср, 19:00",
    room: "Хитровский пер., 2/8 · 204",
    description: "Дизайн исследования, научные источники, методы анализа и подготовка исследовательской части магистерской диссертации.",
    objectives: ["Дизайн исследования", "Поиск научных источников", "Работа с данными", "Подготовка предзащиты"],
    sourceUrl: "https://www.hse.ru/ma/mediaman/courses/1163471151.html",
    targetGrade: 9,
    roundingRule: "hse07",
    pinned: true,
  },
  {
    id: "media-management",
    title: "Основы медиаменеджмента",
    shortTitle: "Медиаменеджмент",
    emoji: "M",
    color: "#E04B35",
    pattern: "blocks",
    module: 1,
    year: 1,
    credits: 3,
    status: "required",
    language: "RU",
    scheduleLabel: "Пн, 18:10",
    room: "М. Трёхсвятительский, 8/2",
    description: "Управленческие модели и ключевые бизнес-процессы современных медиакомпаний.",
    objectives: ["Медиабизнес-модели", "Редакционные процессы", "Команды и роли", "Управленческие решения"],
    sourceUrl: "https://www.hse.ru/ma/mediaman/courses/page2.html?year=2026",
    targetGrade: 8,
    roundingRule: "math",
    pinned: true,
  },
  {
    id: "media-marketing",
    title: "Основы медиамаркетинга",
    shortTitle: "Медиамаркетинг",
    emoji: "↗",
    color: "#0F8B6D",
    pattern: "waves",
    module: 1,
    year: 1,
    credits: 3,
    status: "required",
    language: "RU",
    scheduleLabel: "Чт, 18:10",
    room: "Хитровский пер., 2/8 · 305",
    description: "Аудитории, позиционирование, медиапродукт и продвижение на конкурентном рынке.",
    objectives: ["Сегментация аудиторий", "Позиционирование", "Маркетинговая стратегия", "Метрики"],
    sourceUrl: "https://www.hse.ru/ma/mediaman/courses/1163503739.html",
    targetGrade: 8,
    roundingRule: "math",
    pinned: true,
  },
  {
    id: "media-analytics",
    title: "Медиааналитика",
    shortTitle: "Медиааналитика",
    emoji: "▥",
    color: "#BF7A00",
    pattern: "lines",
    module: 4,
    year: 1,
    credits: 3,
    status: "required",
    language: "RU",
    scheduleLabel: "Модуль 4",
    room: "Будет объявлено",
    description: "Данные и ключевые метрики телевизионной, цифровой, аудио- и коммерческой аналитики.",
    objectives: ["Источники данных", "Метрики медиабизнеса", "Аналитические отчёты", "Учебный кейс"],
    sourceUrl: "https://www.hse.ru/ma/mediaman/courses/1163626272.html",
    targetGrade: 9,
    roundingRule: "math",
    pinned: false,
  },
  {
    id: "magolego-producing",
    title: "Аудиовизуальное продюсирование медиапроектов",
    shortTitle: "Продюсирование",
    emoji: "▶",
    color: "#C23B72",
    pattern: "dots",
    module: 1,
    year: 1,
    credits: 3,
    status: "magolego",
    language: "RU",
    scheduleLabel: "По выбору",
    room: "Офлайн",
    description: "МагоЛего: производство аудиовизуального контента от идеи до размещения.",
    objectives: ["Разработка формата", "Креативное продюсирование", "Линейное производство", "Питчинг"],
    sourceUrl: "https://www.hse.ru/ma/mediaman/magolego",
    targetGrade: 8,
    roundingRule: "math",
    pinned: false,
  },
];

function seedLessons(today: Date): CourseLesson[] {
  const configs = [
    ["media-management", "seminar", ["Медиакомпания как система", "Бизнес-модели медиа", "Редакционные процессы", "Управление продуктом", "Экономика медиакомпании", "Команды и роли", "Стратегия роста", "Разбор командного кейса"]],
    ["media-marketing", "seminar", ["Аудитория и сегментация", "Ценностное предложение", "Позиционирование", "Исследование рынка", "Контент-стратегия", "Дистрибуция", "Маркетинговые метрики", "Защита проекта"]],
    ["research-seminar", "seminar", ["Исследовательская проблема", "Поиск научных источников", "Теоретическая рамка", "Исследовательский вопрос", "Качественные методы", "Количественные методы", "Выборка и данные", "Дизайн исследования", "Пилот", "Предзащита дизайна"]],
    ["ai-media", "workshop", ["ИИ в медиапроизводстве", "Промптинг", "Текстовые модели", "Изображения и видео", "Исследование контента", "Прототипирование", "Этика и право", "Защита прототипа"]],
  ] as const;
  return configs.flatMap(([subjectId, kind, topics], subjectIndex) => topics.map((topic, index) => {
    const score = index < 2 ? 8 + ((index + subjectIndex) % 2) : null;
    const lessonKind = index === topics.length - 1 ? "exam" : subjectId === "research-seminar" ? "nis" : index % 3 === 0 ? "lecture" : kind;
    return {
      id: `lesson-${subjectId}-${index + 1}`,
      subjectId,
      number: index + 1,
      numbers: [index + 1],
      kind: lessonKind,
      title: `${lessonKind === "lecture" ? "Лекция" : lessonKind === "nis" ? "НИС" : lessonKind === "exam" ? "Экзамен" : lessonKind === "workshop" ? "Практическое занятие" : "Семинар"} ${index + 1}`,
      topic,
      topicIds: [`topic-${subjectId}-${index + 1}`],
      date: iso(today, subjectIndex + index * 7, 18),
      grade: score,
      assessmentFormat: "numeric",
      assessmentValue: score === null ? "" : String(score),
      assessmentMin: 0,
      assessmentMax: 10,
      notes: index === 0 ? "Ключевые тезисы и вопросы можно хранить прямо здесь." : "",
    };
  }));
}

function seedTopics(lessons: CourseLesson[]): CourseTopic[] {
  return lessons.map((lesson) => ({ id: lesson.topicIds[0], subjectId: lesson.subjectId, title: lesson.topic || "Без названия", notes: "" }));
}

export function createSeedState(base = new Date()): PlannerState {
  const today = startOfDay(base);
  const semesterEnd = addMonths(today, 4);
  const lessons = seedLessons(today);
  const topics = seedTopics(lessons);
  const managementLessons = lessons.filter((lesson) => lesson.subjectId === "media-management");
  if (managementLessons[1] && managementLessons[0]) managementLessons[1].topicIds.unshift(managementLessons[0].topicIds[0]);
  if (managementLessons[2] && managementLessons[1]) managementLessons[2].topicIds.unshift(managementLessons[1].topicIds[managementLessons[1].topicIds.length - 1]);
  return {
    profile: {
      name: "Вероника",
      program: "Медиаменеджмент",
      year: 1,
      module: 1,
      academicYear: "2026/2027",
      weeklyGoal: 12,
      semesterStart: formatISO(addDays(today, -3), { representation: "date" }),
      semesterEnd: formatISO(semesterEnd, { representation: "date" }),
      theme: "light",
    },
    subjects,
    tasks: [
      {
        id: "task-media-models",
        subjectId: "media-management",
        title: "Разобрать бизнес-модели трёх медиакомпаний",
        type: "seminar",
        dueDate: iso(today, 1, 18),
        plannedDate: iso(today, 0, 20),
        status: "doing",
        priority: "high",
        estimatedMinutes: 120,
        notes: "Сравнить источники выручки, ключевые расходы и роль платформ.",
        subtasks: [
          { id: "sub-1", title: "Выбрать компании", done: true },
          { id: "sub-2", title: "Собрать данные", done: false },
          { id: "sub-3", title: "Сделать выводы", done: false },
        ],
        createdAt: iso(today, -4),
      },
      {
        id: "task-marketing-reading",
        subjectId: "media-marketing",
        title: "Конспект главы о сегментации аудитории",
        type: "reading",
        dueDate: iso(today, 3, 12),
        status: "todo",
        priority: "medium",
        estimatedMinutes: 75,
        notes: "Выписать критерии сегментации и примеры для российского медиарынка.",
        subtasks: [],
        createdAt: iso(today, -2),
      },
      {
        id: "task-research-question",
        subjectId: "research-seminar",
        title: "Сформулировать исследовательский вопрос ВКР",
        type: "project",
        dueDate: iso(today, 6, 20),
        plannedDate: iso(today, 4, 19),
        status: "todo",
        priority: "high",
        estimatedMinutes: 180,
        notes: "Подготовить 3 варианта и проверить связь с эмпирической частью.",
        subtasks: [
          { id: "sub-4", title: "Определить объект", done: false },
          { id: "sub-5", title: "Определить предмет", done: false },
          { id: "sub-6", title: "Проверить доступность данных", done: false },
        ],
        createdAt: iso(today, -1),
      },
      {
        id: "task-ai-tools",
        subjectId: "ai-media",
        title: "Карта ИИ-инструментов для медиаисследований",
        type: "homework",
        dueDate: iso(today, 9, 18),
        status: "todo",
        priority: "medium",
        estimatedMinutes: 150,
        notes: "Не менее 8 инструментов: задача, входные данные, ограничения, стоимость.",
        subtasks: [],
        createdAt: iso(today, 0),
      },
      {
        id: "task-producer-application",
        subjectId: "magolego-producing",
        title: "Подать заявку на МагоЛего",
        type: "other",
        dueDate: iso(today, 12, 23),
        status: "todo",
        priority: "low",
        estimatedMinutes: 30,
        notes: "Проверить отсутствие пересечений в расписании.",
        subtasks: [],
        createdAt: iso(today, 0),
      },
      {
        id: "task-done-intro",
        subjectId: "media-management",
        title: "Вводная лекция и карта курса",
        type: "lecture",
        dueDate: iso(today, -2, 20),
        status: "done",
        priority: "low",
        estimatedMinutes: 45,
        notes: "",
        subtasks: [],
        createdAt: iso(today, -5),
      },
    ],
    grades: [
      { id: "g-ai-prototype", subjectId: "ai-media", title: "Прототип индустриального решения", weight: 0.45, score: null, maxScore: 10, dueDate: iso(today, 42) },
      { id: "g-ai-report", subjectId: "ai-media", title: "Доклад", weight: 0.35, score: 8, maxScore: 10 },
      { id: "g-ai-active", subjectId: "ai-media", title: "Активность", weight: 0.2, score: 9, maxScore: 10 },
      { id: "g-nis-test1", subjectId: "research-seminar", title: "Контрольная работа №1", weight: 0.2, score: 8, maxScore: 10 },
      { id: "g-nis-test2", subjectId: "research-seminar", title: "Контрольная работа №2", weight: 0.2, score: null, maxScore: 10 },
      { id: "g-nis-attendance", subjectId: "research-seminar", title: "Посещаемость", weight: 0.2, score: 10, maxScore: 10 },
      { id: "g-nis-exam", subjectId: "research-seminar", title: "Экзамен", weight: 0.4, score: null, maxScore: 10 },
      { id: "g-mm-case", subjectId: "media-management", title: "Командный кейс", weight: 0.4, score: 8, maxScore: 10 },
      { id: "g-mm-active", subjectId: "media-management", title: "Работа на семинарах", weight: 0.2, score: null, maxScore: 10, calculation: "lesson_average", lessonKind: "seminar" },
      { id: "g-mm-exam", subjectId: "media-management", title: "Экзамен", weight: 0.4, score: null, maxScore: 10 },
      { id: "g-mark-project", subjectId: "media-marketing", title: "Маркетинговый проект", weight: 0.5, score: null, maxScore: 10 },
      { id: "g-mark-tasks", subjectId: "media-marketing", title: "Практические задания", weight: 0.3, score: 8, maxScore: 10 },
      { id: "g-mark-active", subjectId: "media-marketing", title: "Активность", weight: 0.2, score: 9, maxScore: 10 },
      { id: "g-analytics-ind", subjectId: "media-analytics", title: "Индивидуальное задание", weight: 0.3, score: null, maxScore: 10 },
      { id: "g-analytics-active", subjectId: "media-analytics", title: "Активность", weight: 0.2, score: null, maxScore: 10 },
      { id: "g-analytics-group", subjectId: "media-analytics", title: "Групповое задание", weight: 0.5, score: null, maxScore: 10 },
    ],
    topics,
    lessons,
    notes: [
      {
        id: "note-management-1",
        subjectId: "media-management",
        title: "Лекция 1 · Медиакомпания как система",
        body: "Медиакомпания одновременно управляет продуктом, аудиторией, дистрибуцией и несколькими потоками дохода. На следующей лекции уточнить различия платформенной и редакционной моделей.",
        kind: "lecture",
        tags: ["бизнес-модель", "введение"],
        updatedAt: iso(today, -2),
      },
      {
        id: "note-thesis-idea",
        subjectId: "research-seminar",
        title: "Гипотеза для исследования",
        body: "Связать управленческие решения медиакомпаний с изменением форматов короткого видео и проверить на нескольких кейсах.",
        kind: "idea",
        tags: ["ВКР", "гипотеза"],
        updatedAt: iso(today, -1),
      },
    ],
    schedule: [
      { id: "sch-mm", subjectId: "media-management", weekday: 1, start: "18:10", end: "21:00", location: "М. Трёхсвятительский, 8/2", format: "seminar", parity: "every" },
      { id: "sch-ai", subjectId: "ai-media", weekday: 2, start: "18:10", end: "21:00", location: "Покровский б-р, 11 · R403", format: "seminar", parity: "every" },
      { id: "sch-nis", subjectId: "research-seminar", weekday: 3, start: "19:00", end: "21:50", location: "Хитровский пер., 2/8 · 204", format: "seminar", parity: "every" },
      { id: "sch-mark", subjectId: "media-marketing", weekday: 4, start: "18:10", end: "21:00", location: "Хитровский пер., 2/8 · 305", format: "lecture", parity: "every" },
    ],
    materials: [
      { id: "mat-hse-courses", subjectId: null, name: "Учебные курсы программы", label: "Сайт программы", kind: "link", storage: "link", url: "https://www.hse.ru/ma/mediaman/courses?year=2026", createdAt: iso(today, -3) },
      { id: "mat-ai-pud", subjectId: "ai-media", name: "Программа дисциплины и формула оценки", label: "Программа курса", kind: "link", storage: "link", url: "https://www.hse.ru/ma/mediaman/courses/1163626217.html", createdAt: iso(today, -3) },
      { id: "mat-nis-pud", subjectId: "research-seminar", name: "Методология и методы медиаисследований", label: "Программа курса", kind: "link", storage: "link", url: "https://www.hse.ru/ma/mediaman/courses/1163471151.html", createdAt: iso(today, -3) },
      { id: "mat-mm-recording", subjectId: "media-management", name: "Лекция 1 · Медиакомпания как система", label: "Запись лекции", kind: "recording", storage: "link", url: "https://edu.hse.ru/", createdAt: iso(today, -2) },
      { id: "mat-mm-slides", subjectId: "media-management", name: "Бизнес-модели медиакомпаний", label: "Презентация · неделя 1", kind: "presentation", storage: "link", url: "https://edu.hse.ru/", createdAt: iso(today, -2) },
      { id: "mat-nis-book", subjectId: "research-seminar", name: "Как организовать и представить исследовательский проект", label: "В. В. Радаев · учебник", kind: "textbook", storage: "link", url: "https://znanium.ru/catalog/product/2017208", createdAt: iso(today, -1) },
    ],
    diplomaGrades: [],
    coursework: {
      title: "Курсовая работа 1 курса",
      blocks: [
        { id: "coursework-object", title: "Объект и предмет", content: "" },
        { id: "coursework-tasks", title: "Задачи", content: "" },
      ],
      supervisor: "Руководитель не выбран",
      stage: "Выбор темы и исследовательского вопроса",
      progress: 0,
      researchQuestion: "",
      chapters: [],
      milestones: [],
    },
    thesis: {
      title: "Рабочая тема магистерской диссертации",
      blocks: [
        { id: "thesis-object", title: "Объект и предмет", content: "Добавьте объект, предмет и границы исследования." },
        { id: "thesis-tasks", title: "Задачи", content: "1. Собрать теоретическую рамку\n2. Выбрать кейсы\n3. Разработать методику\n4. Провести анализ" },
      ],
      supervisor: "Научный руководитель не выбран",
      stage: "Поиск темы и исследовательского вопроса",
      progress: 12,
      targetWords: 25000,
      currentWords: 1850,
      nextMeeting: iso(today, 14, 17),
      researchQuestion: "Как управленческие решения медиакомпаний влияют на развитие новых цифровых форматов?",
      chapters: [
        { id: "chapter-intro", title: "Введение и постановка проблемы", progress: 35, status: "doing", deadline: iso(today, 45) },
        { id: "chapter-theory", title: "Теоретическая рамка", progress: 10, status: "todo", deadline: iso(today, 72) },
        { id: "chapter-method", title: "Методология исследования", progress: 5, status: "todo", deadline: iso(today, 95) },
        { id: "chapter-analysis", title: "Эмпирическая часть", progress: 0, status: "todo", deadline: iso(today, 145) },
        { id: "chapter-conclusion", title: "Выводы и заключение", progress: 0, status: "todo", deadline: iso(today, 190) },
      ],
      milestones: [
        { id: "mile-topic", title: "Утвердить тему и руководителя", deadline: iso(today, 30), done: false, note: "Подготовить 2–3 формулировки" },
        { id: "mile-bibliography", title: "Собрать базовую библиографию", deadline: iso(today, 55), done: false, note: "Не менее 25 релевантных источников" },
        { id: "mile-design", title: "Защитить дизайн исследования", deadline: iso(today, 90), done: false, note: "Вопрос, гипотеза, выборка и методы" },
        { id: "mile-pilot", title: "Провести пилот исследования", deadline: iso(today, 130), done: false, note: "Проверить инструментарий" },
      ],
    },
    activities: [
      { id: "act-magolego", title: "Выбор курса МагоЛего", category: "magolego", status: "doing", date: iso(today, 12), deadline: iso(today, 12), progress: 45, link: "https://www.hse.ru/ma/mediaman/magolego", notes: "Сравнить продюсирование и консалтинг в медиа." },
      { id: "act-internship", title: "Подобрать площадку для практики", category: "internship", status: "todo", date: iso(today, 35), deadline: iso(today, 35), progress: 15, link: "https://www.hse.ru/ma/mediaman/internships", notes: "Составить шорт-лист из 5 медиакомпаний." },
      { id: "act-career", title: "Карьерная консультация", category: "career", status: "todo", date: iso(today, 20), progress: 0, link: "https://career.hse.ru/", notes: "Обновить резюме и собрать вопросы." },
      { id: "act-club", title: "Открытая лекция Института медиа", category: "event", status: "todo", date: iso(today, 8), progress: 0, notes: "Добавить тезисы в базу знаний после мероприятия." },
    ],
    sessions: [
      { id: "session-1", subjectId: "media-management", date: iso(today, -2), minutes: 70, focusScore: 4 },
      { id: "session-2", subjectId: "research-seminar", date: iso(today, -1), minutes: 55, focusScore: 5 },
      { id: "session-3", subjectId: "media-marketing", date: iso(today, 0), minutes: 45, focusScore: 4 },
    ],
  };
}
